name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      version:
        description: Version
      env:
        description: Environment
        type: environment
        required: true
        default: "Production"

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Windows Build
            os: windows-latest
            architecture: x64
            artifact: windows
            upload_path_suffix: '/*'
          - name: MacOS Build
            os: macos-latest
            architecture: x64
            artifact: macos
            upload_path_suffix: '.zip'
          - name: Linux Build
            os: ubuntu-20.04
            architecture: x64
            artifact: linux
            upload_path_suffix: '/*'
    
    runs-on: ${{ matrix.os }}
    environment: ${{ github.event.inputs.env || 'Development' }}
    
    defaults:
      run:
        shell: bash
    
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      MACOSX_DEPLOYMENT_TARGET: 10.15
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Add keys
        run: |
            echo "$SEED_KEY" > keys/seed_key.py
            echo "$BUILD_KEY" > keys/build_key.txt
        env:
          SEED_KEY: ${{ secrets.SEED_KEY }}
          BUILD_KEY: ${{ secrets.BUILD_KEY }}
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: ${{ matrix.architecture }}
          cache: 'pip' # Cache all pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements_full.txt
          python -m pip install PyInstaller
      - name: Install any missing Qt dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev
          sudo apt-get install -y libxcb-cursor0
      - name: Set variables
        id: vars
        run: |
          USER_INPUT_VERSION=${{ github.event.inputs.version }}
          TXT_VERSION=$(cat version.txt)
          GIT_SHA_SHORT=$(git rev-parse --short=7 ${{ github.sha }})
          echo "full_version=${USER_INPUT_VERSION:-$TXT_VERSION-$GIT_SHA_SHORT}" >> $GITHUB_OUTPUT
      - name: Set version
        id: version
        run: |
          echo ${{ steps.vars.outputs.full_version }} > version.txt
      - name: Build Python App
        run: python -m PyInstaller --log-level=WARN wwrando.spec
      - name: Bundle Python App
        run: python build.py
      - name: Upload Python App
        uses: actions/upload-artifact@v3
        with:
          name: wwrando-${{ steps.vars.outputs.full_version }}-${{ matrix.artifact }}-${{ matrix.architecture }}
          path: dist/release_archive_${{ steps.vars.outputs.full_version }}_${{ matrix.architecture }}${{ matrix.upload_path_suffix }}
